# Jenkins containers written with Serverless!

service: jenkins

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}

# Instead of functions you can add CloudFormation resources
resources:
  Parameters:
    JenkinsUserNameInput:
      Description: The Jenkins user name to be created and granted access mentioned in the template description.
      Type: String
      Default: ${opt:username, 'JenkinsUser'}
    JenkinsUserPasswordInput:
      Description: The Jenkins user password used for the first time access. This should be changed upon the first login.
      Type: String
      Default: "myP@ssW0rd"
  Resources:
    JenkinsUser:
      Type: "AWS::IAM::User"
      Properties:
        UserName: !Ref JenkinsUserNameInput
        LoginProfile:
          Password: !Ref JenkinsUserPasswordInput
        Policies:
        - PolicyName: JenkinsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:*
              Resource:
              - arn:aws:s3:::*
            - Effect: Deny
              Action:
              - s3:GetObject
              - s3:DeleteObject
              Resource:
              - arn:aws:s3:::*