AWSTemplateFormatVersion: '2010-09-09'
Description: DevOps Project Role for Jenkins Server

Parameters:
  ProjectName:
    Type: String
    Description: A name that will be given to the CodeBuild project that will be created for you
    Default: JenkinsSeed
  GithubCloneUrl:
    Type: String
    Description: the clone URL of the repository containing the source code for the website
    Default: https://github.com/dcroswell/jenkins-starter-project.git
  DomainName:
    Type: String
    Description: Fully qualified domain name under which the site will be accessible
    Default: www.google.com

Resources:
  CodeBuildIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
  RolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Sub ProjectName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}:*
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
          - Effect: 'Allow'
            Resource:
              - !Sub arn:aws:s3:::codepipeline-${AWS::Region}*
              - !Sub arn:aws:s3:::${DomainName}*
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
      Roles:
        -
          Ref: "CodeBuildIAMRole"
Outputs:
  CodeBuildIAMRole:
    Description: The ID of the Codebuild Role.
    Value: !Ref CodeBuildIAMRole
    Export:
      Name: !Sub "CodeBuildIAMRole"